-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;
-- Create roles
CREATE ROLE IF NOT EXISTS SPOTIFY_ETL_ROLE;
CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS SPOTIFY_ETL_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Spotify ETL operations';

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS SPOTIFY_DB;

USE DATABASE SPOTIFY_DB;

CREATE SCHEMA IF NOT EXISTS RAW_LAYER;        -- Landing zone (raw CSVs)
CREATE SCHEMA IF NOT EXISTS STAGING_LAYER;    -- Cleaned/validated data
CREATE SCHEMA IF NOT EXISTS WAREHOUSE_LAYER;  -- Final analytics tables
CREATE SCHEMA IF NOT EXISTS AUDIT_LAYER;      -- ETL logs and metadata

-- Grant privileges
GRANT USAGE ON WAREHOUSE SPOTIFY_ETL_WH TO ROLE SPOTIFY_ETL_ROLE;
GRANT ALL ON DATABASE SPOTIFY_DB TO ROLE SPOTIFY_ETL_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE SPOTIFY_DB TO ROLE SPOTIFY_ETL_ROLE;

GRANT ROLE SPOTIFY_ETL_ROLE TO USER ASHUTOSHKR15081985;
