-- Automated Spotify pipeline using append-only Streams with MERGE-based CDC and audit logging
-- Co-authored with CoCo
USE SPOTIFY_DB;

USE SCHEMA RAW_LAYER;

-- ================================================
-- STREAMS - Recreate as append-only (flushes stale data, starts fresh)
-- ================================================

CREATE OR REPLACE STREAM STREAM_RAW_SONGS
    ON TABLE RAW_LAYER.RAW_SONGS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STREAM_RAW_ARTISTS
    ON TABLE RAW_LAYER.RAW_ARTISTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STREAM_RAW_ALBUMS
    ON TABLE RAW_LAYER.RAW_ALBUMS
    APPEND_ONLY = TRUE;

-- ================================================
-- TASKS - Orchestrate the full pipeline
-- ================================================

-- Cleanup: Suspend and drop existing tasks before recreating (children first, then root)
ALTER TASK IF EXISTS TASK_LOAD_FACTS SUSPEND;
ALTER TASK IF EXISTS TASK_LOAD_DIMENSIONS_ALBUMS SUSPEND;
ALTER TASK IF EXISTS TASK_LOAD_DIMENSIONS_ARTISTS SUSPEND;
ALTER TASK IF EXISTS TASK_LOAD_STAGING_SONGS SUSPEND;
ALTER TASK IF EXISTS TASK_LOAD_STAGING_ARTISTS SUSPEND;
ALTER TASK IF EXISTS TASK_LOAD_STAGING_ALBUMS SUSPEND;
ALTER TASK IF EXISTS TASK_ROOT_SPOTIFY_PIPELINE SUSPEND;

DROP TASK IF EXISTS TASK_LOAD_FACTS;
DROP TASK IF EXISTS TASK_LOAD_DIMENSIONS_ALBUMS;
DROP TASK IF EXISTS TASK_LOAD_DIMENSIONS_ARTISTS;
DROP TASK IF EXISTS TASK_LOAD_STAGING_SONGS;
DROP TASK IF EXISTS TASK_LOAD_STAGING_ARTISTS;
DROP TASK IF EXISTS TASK_LOAD_STAGING_ALBUMS;
DROP TASK IF EXISTS TASK_ROOT_SPOTIFY_PIPELINE;

-- ================================================
-- Root Task: Runs every 5 minutes (Europe/Berlin)
-- ================================================
CREATE OR REPLACE TASK TASK_ROOT_SPOTIFY_PIPELINE
    WAREHOUSE = SPOTIFY_ETL_WH
    SCHEDULE  = 'USING CRON */5 * * * * Europe/Berlin'
AS
    SELECT 'Pipeline triggered at: ' || CURRENT_TIMESTAMP();

-- ================================================
-- Task: MERGE Songs into Staging from Stream (with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_STAGING_SONGS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_ROOT_SPOTIFY_PIPELINE
WHEN
    SYSTEM$STREAM_HAS_DATA('RAW_LAYER.STREAM_RAW_SONGS')
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_merged NUMBER := 0;
    LET v_rows_deleted NUMBER := 0;

    BEGIN TRANSACTION;

    -- MERGE inserts and updates from stream into staging
    MERGE INTO STAGING_LAYER.STG_SONGS AS tgt
    USING (
        SELECT
            TRIM(SONG_ID) AS SONG_ID,
            TRIM(SONG_NAME) AS SONG_NAME,
            TRY_TO_NUMBER(SONG_DURATION) AS SONG_DURATION_MS,
            FLOOR(TRY_TO_NUMBER(SONG_DURATION) / 60000) AS DURATION_MINUTES,
            ROUND((TRY_TO_NUMBER(SONG_DURATION)/1000) - 
                  (FLOOR(TRY_TO_NUMBER(SONG_DURATION)/60000)*60)) AS DURATION_SECONDS,
            TRIM(SONG_URL) AS SONG_URL,
            TRY_TO_TIMESTAMP(SONG_ADDED) AS SONG_ADDED_TIMESTAMP,
            DATE(TRY_TO_TIMESTAMP(SONG_ADDED)) AS SONG_ADDED_DATE,
            TRIM(ALBUM_ID) AS ALBUM_ID,
            TRIM(ARTIST_ID) AS ARTIST_ID,
            CASE
                WHEN SONG_ID IS NULL                       THEN 'MISSING_SONG_ID'
                WHEN TRY_TO_NUMBER(SONG_DURATION) IS NULL  THEN 'INVALID_DURATION'
                ELSE 'VALID'
            END AS DATA_QUALITY_FLAG,
            _LOAD_TIMESTAMP
        FROM RAW_LAYER.STREAM_RAW_SONGS
    ) AS src
    ON tgt.SONG_ID = src.SONG_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.SONG_NAME = src.SONG_NAME,
        tgt.SONG_DURATION_MS = src.SONG_DURATION_MS,
        tgt.DURATION_MINUTES = src.DURATION_MINUTES,
        tgt.DURATION_SECONDS = src.DURATION_SECONDS,
        tgt.SONG_URL = src.SONG_URL,
        tgt.SONG_ADDED_TIMESTAMP = src.SONG_ADDED_TIMESTAMP,
        tgt.SONG_ADDED_DATE = src.SONG_ADDED_DATE,
        tgt.ALBUM_ID = src.ALBUM_ID,
        tgt.ARTIST_ID = src.ARTIST_ID,
        tgt.DATA_QUALITY_FLAG = src.DATA_QUALITY_FLAG,
        tgt._LOAD_TIMESTAMP = src._LOAD_TIMESTAMP,
        tgt._TRANSFORM_TIMESTAMP = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        SONG_ID, SONG_NAME, SONG_DURATION_MS, DURATION_MINUTES, DURATION_SECONDS,
        SONG_URL, SONG_ADDED_TIMESTAMP, SONG_ADDED_DATE,
        ALBUM_ID, ARTIST_ID, DATA_QUALITY_FLAG,
        _LOAD_TIMESTAMP, _TRANSFORM_TIMESTAMP
    ) VALUES (
        src.SONG_ID, src.SONG_NAME, src.SONG_DURATION_MS, src.DURATION_MINUTES, src.DURATION_SECONDS,
        src.SONG_URL, src.SONG_ADDED_TIMESTAMP, src.SONG_ADDED_DATE,
        src.ALBUM_ID, src.ARTIST_ID, src.DATA_QUALITY_FLAG,
        src._LOAD_TIMESTAMP, CURRENT_TIMESTAMP()
    );
    v_rows_merged := SQLROWCOUNT;

    -- Delete stale records: guard + lookup raw with NEW status
    DELETE FROM STAGING_LAYER.STG_SONGS
    WHERE (SELECT COUNT(*) FROM RAW_LAYER.RAW_SONGS WHERE LOAD_STATUS = 'NEW') > 0
    AND SONG_ID NOT IN (
        SELECT TRIM(SONG_ID) FROM RAW_LAYER.RAW_SONGS WHERE LOAD_STATUS = 'NEW'
    );
    v_rows_deleted := SQLROWCOUNT;

    -- Mark consumed records as LOADED
    UPDATE RAW_LAYER.RAW_SONGS
    SET LOAD_STATUS = 'LOADED'
    WHERE LOAD_STATUS = 'NEW';

    -- Audit log
    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_STAGING_SONGS', 'STAGING', 'MERGE+DELETE', 'STG_SONGS', :v_rows_merged, 0, :v_rows_deleted, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- ================================================
-- Task: MERGE Artists into Staging from Stream (with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_STAGING_ARTISTS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_ROOT_SPOTIFY_PIPELINE
WHEN
    SYSTEM$STREAM_HAS_DATA('RAW_LAYER.STREAM_RAW_ARTISTS')
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_merged NUMBER := 0;
    LET v_rows_deleted NUMBER := 0;

    BEGIN TRANSACTION;

    MERGE INTO STAGING_LAYER.STG_ARTISTS AS tgt
    USING (
        SELECT
            TRIM(ARTIST_ID) AS ARTIST_ID,
            TRIM(ARTIST_NAME) AS ARTIST_NAME,
            TRIM(EXTERNAL_URL) AS EXTERNAL_URL,
            CASE
                WHEN ARTIST_ID IS NULL   THEN 'MISSING_ARTIST_ID'
                WHEN ARTIST_NAME IS NULL THEN 'MISSING_ARTIST_NAME'
                ELSE 'VALID'
            END AS DATA_QUALITY_FLAG,
            _LOAD_TIMESTAMP
        FROM RAW_LAYER.STREAM_RAW_ARTISTS
    ) AS src
    ON tgt.ARTIST_ID = src.ARTIST_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.ARTIST_NAME = src.ARTIST_NAME,
        tgt.EXTERNAL_URL = src.EXTERNAL_URL,
        tgt.DATA_QUALITY_FLAG = src.DATA_QUALITY_FLAG,
        tgt._LOAD_TIMESTAMP = src._LOAD_TIMESTAMP,
        tgt._TRANSFORM_TIMESTAMP = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        ARTIST_ID, ARTIST_NAME, EXTERNAL_URL,
        DATA_QUALITY_FLAG, _LOAD_TIMESTAMP, _TRANSFORM_TIMESTAMP
    ) VALUES (
        src.ARTIST_ID, src.ARTIST_NAME, src.EXTERNAL_URL,
        src.DATA_QUALITY_FLAG, src._LOAD_TIMESTAMP, CURRENT_TIMESTAMP()
    );
    v_rows_merged := SQLROWCOUNT;

    DELETE FROM STAGING_LAYER.STG_ARTISTS
    WHERE (SELECT COUNT(*) FROM RAW_LAYER.RAW_ARTISTS WHERE LOAD_STATUS = 'NEW') > 0
    AND ARTIST_ID NOT IN (
        SELECT TRIM(ARTIST_ID) FROM RAW_LAYER.RAW_ARTISTS WHERE LOAD_STATUS = 'NEW'
    );
    v_rows_deleted := SQLROWCOUNT;

    UPDATE RAW_LAYER.RAW_ARTISTS
    SET LOAD_STATUS = 'LOADED'
    WHERE LOAD_STATUS = 'NEW';

    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_STAGING_ARTISTS', 'STAGING', 'MERGE+DELETE', 'STG_ARTISTS', :v_rows_merged, 0, :v_rows_deleted, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- ================================================
-- Task: MERGE Albums into Staging from Stream (with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_STAGING_ALBUMS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_ROOT_SPOTIFY_PIPELINE
WHEN
    SYSTEM$STREAM_HAS_DATA('RAW_LAYER.STREAM_RAW_ALBUMS')
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_merged NUMBER := 0;
    LET v_rows_deleted NUMBER := 0;

    BEGIN TRANSACTION;

    MERGE INTO STAGING_LAYER.STG_ALBUMS AS tgt
    USING (
        SELECT
            TRIM(ALBUM_ID) AS ALBUM_ID,
            TRIM(ALBUM_NAME) AS ALBUM_NAME,
            TRY_TO_DATE(ALBUM_RELEASE_DATE) AS ALBUM_RELEASE_DATE,
            TRY_TO_NUMBER(ALBUM_TOTAL_TRACKS) AS ALBUM_TOTAL_TRACKS,
            TRIM(ALBUM_URL) AS ALBUM_URL,
            YEAR(TRY_TO_DATE(ALBUM_RELEASE_DATE)) AS RELEASE_YEAR,
            CASE
                WHEN ALBUM_ID IS NULL                        THEN 'MISSING_ALBUM_ID'
                WHEN TRY_TO_DATE(ALBUM_RELEASE_DATE) IS NULL THEN 'INVALID_RELEASE_DATE'
                ELSE 'VALID'
            END AS DATA_QUALITY_FLAG,
            _LOAD_TIMESTAMP
        FROM RAW_LAYER.STREAM_RAW_ALBUMS
    ) AS src
    ON tgt.ALBUM_ID = src.ALBUM_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.ALBUM_NAME = src.ALBUM_NAME,
        tgt.ALBUM_RELEASE_DATE = src.ALBUM_RELEASE_DATE,
        tgt.ALBUM_TOTAL_TRACKS = src.ALBUM_TOTAL_TRACKS,
        tgt.ALBUM_URL = src.ALBUM_URL,
        tgt.RELEASE_YEAR = src.RELEASE_YEAR,
        tgt.DATA_QUALITY_FLAG = src.DATA_QUALITY_FLAG,
        tgt._LOAD_TIMESTAMP = src._LOAD_TIMESTAMP,
        tgt._TRANSFORM_TIMESTAMP = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE,
        ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR,
        DATA_QUALITY_FLAG, _LOAD_TIMESTAMP, _TRANSFORM_TIMESTAMP
    ) VALUES (
        src.ALBUM_ID, src.ALBUM_NAME, src.ALBUM_RELEASE_DATE,
        src.ALBUM_TOTAL_TRACKS, src.ALBUM_URL, src.RELEASE_YEAR,
        src.DATA_QUALITY_FLAG, src._LOAD_TIMESTAMP, CURRENT_TIMESTAMP()
    );
    v_rows_merged := SQLROWCOUNT;

    DELETE FROM STAGING_LAYER.STG_ALBUMS
    WHERE (SELECT COUNT(*) FROM RAW_LAYER.RAW_ALBUMS WHERE LOAD_STATUS = 'NEW') > 0
    AND ALBUM_ID NOT IN (
        SELECT TRIM(ALBUM_ID) FROM RAW_LAYER.RAW_ALBUMS WHERE LOAD_STATUS = 'NEW'
    );
    v_rows_deleted := SQLROWCOUNT;

    UPDATE RAW_LAYER.RAW_ALBUMS
    SET LOAD_STATUS = 'LOADED'
    WHERE LOAD_STATUS = 'NEW';

    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_STAGING_ALBUMS', 'STAGING', 'MERGE+DELETE', 'STG_ALBUMS', :v_rows_merged, 0, :v_rows_deleted, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- ================================================
-- Task: Load Dimensions - Artists (SCD Type 2 with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_DIMENSIONS_ARTISTS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_LOAD_STAGING_ARTISTS
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_closed NUMBER := 0;
    LET v_rows_inserted NUMBER := 0;

    BEGIN TRANSACTION;

    -- MERGE: Close records that are changed or deleted
    MERGE INTO WAREHOUSE_LAYER.DIM_ARTISTS AS tgt
    USING (
        SELECT ARTIST_ID, ARTIST_NAME, EXTERNAL_URL, 'UPSERT' AS ACTION
        FROM STAGING_LAYER.STG_ARTISTS
        WHERE DATA_QUALITY_FLAG = 'VALID'
        UNION ALL
        SELECT d.ARTIST_ID, NULL, NULL, 'DELETE'
        FROM WAREHOUSE_LAYER.DIM_ARTISTS d
        WHERE d.IS_CURRENT = TRUE
        AND d.ARTIST_ID NOT IN (SELECT ARTIST_ID FROM STAGING_LAYER.STG_ARTISTS)
    ) AS src
    ON tgt.ARTIST_ID = src.ARTIST_ID AND tgt.IS_CURRENT = TRUE
    WHEN MATCHED AND src.ACTION = 'DELETE' THEN
        UPDATE SET tgt.EFF_END_DATE = CURRENT_DATE() - 1, tgt.IS_CURRENT = FALSE, tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND src.ACTION = 'UPSERT'
        AND (tgt.ARTIST_NAME != src.ARTIST_NAME OR tgt.EXTERNAL_URL != src.EXTERNAL_URL) THEN
        UPDATE SET tgt.EFF_END_DATE = CURRENT_DATE() - 1, tgt.IS_CURRENT = FALSE, tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.ACTION = 'UPSERT' THEN
        INSERT (ARTIST_ID, ARTIST_NAME, EXTERNAL_URL, EFF_START_DATE, EFF_END_DATE, IS_CURRENT)
        VALUES (src.ARTIST_ID, src.ARTIST_NAME, src.EXTERNAL_URL, CURRENT_DATE(), NULL, TRUE);
    v_rows_closed := SQLROWCOUNT;

    -- INSERT: new current version for closed records
    INSERT INTO WAREHOUSE_LAYER.DIM_ARTISTS (
        ARTIST_ID, ARTIST_NAME, EXTERNAL_URL,
        EFF_START_DATE, EFF_END_DATE, IS_CURRENT
    )
    SELECT ARTIST_ID, ARTIST_NAME, EXTERNAL_URL, CURRENT_DATE(), NULL, TRUE
    FROM STAGING_LAYER.STG_ARTISTS
    WHERE DATA_QUALITY_FLAG = 'VALID'
    AND ARTIST_ID NOT IN (
        SELECT ARTIST_ID FROM WAREHOUSE_LAYER.DIM_ARTISTS WHERE IS_CURRENT = TRUE
    );
    v_rows_inserted := SQLROWCOUNT;

    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_DIMENSIONS_ARTISTS', 'WAREHOUSE', 'SCD2_MERGE+INSERT', 'DIM_ARTISTS', :v_rows_inserted, :v_rows_closed, 0, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- ================================================
-- Task: Load Dimensions - Albums (SCD Type 2 with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_DIMENSIONS_ALBUMS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_LOAD_STAGING_ALBUMS
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_closed NUMBER := 0;
    LET v_rows_inserted NUMBER := 0;

    BEGIN TRANSACTION;

    MERGE INTO WAREHOUSE_LAYER.DIM_ALBUMS AS tgt
    USING (
        SELECT ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE, ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR, 'UPSERT' AS ACTION
        FROM STAGING_LAYER.STG_ALBUMS
        WHERE DATA_QUALITY_FLAG = 'VALID'
        UNION ALL
        SELECT d.ALBUM_ID, NULL, NULL, NULL, NULL, NULL, 'DELETE'
        FROM WAREHOUSE_LAYER.DIM_ALBUMS d
        WHERE d.IS_CURRENT = TRUE
        AND d.ALBUM_ID NOT IN (SELECT ALBUM_ID FROM STAGING_LAYER.STG_ALBUMS)
    ) AS src
    ON tgt.ALBUM_ID = src.ALBUM_ID AND tgt.IS_CURRENT = TRUE
    WHEN MATCHED AND src.ACTION = 'DELETE' THEN
        UPDATE SET tgt.EFF_END_DATE = CURRENT_DATE() - 1, tgt.IS_CURRENT = FALSE, tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN MATCHED AND src.ACTION = 'UPSERT'
        AND (tgt.ALBUM_NAME != src.ALBUM_NAME OR tgt.ALBUM_RELEASE_DATE != src.ALBUM_RELEASE_DATE
             OR tgt.ALBUM_TOTAL_TRACKS != src.ALBUM_TOTAL_TRACKS OR tgt.ALBUM_URL != src.ALBUM_URL) THEN
        UPDATE SET tgt.EFF_END_DATE = CURRENT_DATE() - 1, tgt.IS_CURRENT = FALSE, tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.ACTION = 'UPSERT' THEN
        INSERT (ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE, ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR,
                EFF_START_DATE, EFF_END_DATE, IS_CURRENT)
        VALUES (src.ALBUM_ID, src.ALBUM_NAME, src.ALBUM_RELEASE_DATE, src.ALBUM_TOTAL_TRACKS, src.ALBUM_URL, src.RELEASE_YEAR,
                CURRENT_DATE(), NULL, TRUE);
    v_rows_closed := SQLROWCOUNT;

    INSERT INTO WAREHOUSE_LAYER.DIM_ALBUMS (
        ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE,
        ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR,
        EFF_START_DATE, EFF_END_DATE, IS_CURRENT
    )
    SELECT ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE, ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR,
           CURRENT_DATE(), NULL, TRUE
    FROM STAGING_LAYER.STG_ALBUMS
    WHERE DATA_QUALITY_FLAG = 'VALID'
    AND ALBUM_ID NOT IN (
        SELECT ALBUM_ID FROM WAREHOUSE_LAYER.DIM_ALBUMS WHERE IS_CURRENT = TRUE
    );
    v_rows_inserted := SQLROWCOUNT;

    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_DIMENSIONS_ALBUMS', 'WAREHOUSE', 'SCD2_MERGE+INSERT', 'DIM_ALBUMS', :v_rows_inserted, :v_rows_closed, 0, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- Add IS_VALID column to fact table for soft-delete tracking
-- IS_VALID column already exists on FACT_SONGS (added previously)
-- ALTER TABLE WAREHOUSE_LAYER.FACT_SONGS ADD COLUMN IF NOT EXISTS IS_VALID BOOLEAN DEFAULT TRUE;

-- ================================================
-- Task: Load Fact Table using MERGE (with audit)
-- ================================================
CREATE OR REPLACE TASK TASK_LOAD_FACTS
    WAREHOUSE = SPOTIFY_ETL_WH
    AFTER TASK_LOAD_DIMENSIONS_ARTISTS, TASK_LOAD_DIMENSIONS_ALBUMS
AS
BEGIN
    LET v_start TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET v_run_id VARCHAR := TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS');
    LET v_rows_merged NUMBER := 0;
    LET v_rows_invalidated NUMBER := 0;
    LET v_rows_revalidated NUMBER := 0;

    BEGIN TRANSACTION;

    MERGE INTO WAREHOUSE_LAYER.FACT_SONGS AS tgt
    USING (
        SELECT
            s.SONG_ID,
            a.ARTIST_SK,
            al.ALBUM_SK,
            s.SONG_NAME,
            s.SONG_DURATION_MS,
            s.DURATION_MINUTES,
            s.DURATION_SECONDS,
            s.SONG_URL,
            s.SONG_ADDED_TIMESTAMP,
            s.SONG_ADDED_DATE
        FROM STAGING_LAYER.STG_SONGS s
        LEFT JOIN WAREHOUSE_LAYER.DIM_ARTISTS a
            ON s.ARTIST_ID = a.ARTIST_ID AND a.IS_CURRENT = TRUE
        LEFT JOIN WAREHOUSE_LAYER.DIM_ALBUMS al
            ON s.ALBUM_ID = al.ALBUM_ID AND al.IS_CURRENT = TRUE
        WHERE s.DATA_QUALITY_FLAG = 'VALID'
    ) AS src
    ON tgt.SONG_ID = src.SONG_ID
    WHEN MATCHED AND (
        tgt.ARTIST_SK != src.ARTIST_SK
        OR tgt.ALBUM_SK != src.ALBUM_SK
        OR tgt.SONG_NAME != src.SONG_NAME
        OR tgt.SONG_DURATION_MS != src.SONG_DURATION_MS
        OR tgt.SONG_URL != src.SONG_URL
        OR tgt.SONG_ADDED_TIMESTAMP != src.SONG_ADDED_TIMESTAMP
    ) THEN UPDATE SET
        tgt.ARTIST_SK = src.ARTIST_SK,
        tgt.ALBUM_SK = src.ALBUM_SK,
        tgt.SONG_NAME = src.SONG_NAME,
        tgt.SONG_DURATION_MS = src.SONG_DURATION_MS,
        tgt.DURATION_MINUTES = src.DURATION_MINUTES,
        tgt.DURATION_SECONDS = src.DURATION_SECONDS,
        tgt.SONG_URL = src.SONG_URL,
        tgt.SONG_ADDED_TIMESTAMP = src.SONG_ADDED_TIMESTAMP,
        tgt.SONG_ADDED_DATE = src.SONG_ADDED_DATE
    WHEN NOT MATCHED THEN INSERT (
        SONG_ID, ARTIST_SK, ALBUM_SK, SONG_NAME,
        SONG_DURATION_MS, DURATION_MINUTES, DURATION_SECONDS,
        SONG_URL, SONG_ADDED_TIMESTAMP, SONG_ADDED_DATE
    ) VALUES (
        src.SONG_ID, src.ARTIST_SK, src.ALBUM_SK, src.SONG_NAME,
        src.SONG_DURATION_MS, src.DURATION_MINUTES, src.DURATION_SECONDS,
        src.SONG_URL, src.SONG_ADDED_TIMESTAMP, src.SONG_ADDED_DATE
    );
    v_rows_merged := SQLROWCOUNT;

    -- Soft delete: mark songs no longer in staging as invalid
    UPDATE WAREHOUSE_LAYER.FACT_SONGS
    SET IS_VALID = FALSE
    WHERE SONG_ID NOT IN (SELECT SONG_ID FROM STAGING_LAYER.STG_SONGS)
    AND IS_VALID = TRUE;
    v_rows_invalidated := SQLROWCOUNT;

    -- Re-validate songs that reappear in staging
    UPDATE WAREHOUSE_LAYER.FACT_SONGS
    SET IS_VALID = TRUE
    WHERE SONG_ID IN (SELECT SONG_ID FROM STAGING_LAYER.STG_SONGS WHERE DATA_QUALITY_FLAG = 'VALID')
    AND IS_VALID = FALSE;
    v_rows_revalidated := SQLROWCOUNT;

    INSERT INTO RAW_LAYER.ETL_AUDIT_LOG (PIPELINE_RUN_ID, TASK_NAME, TASK_LAYER, OPERATION, TARGET_TABLE, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, STATUS, START_TIME, END_TIME, DURATION_SECONDS)
    SELECT :v_run_id, 'TASK_LOAD_FACTS', 'WAREHOUSE', 'MERGE+SOFT_DELETE', 'FACT_SONGS', :v_rows_merged, :v_rows_revalidated, :v_rows_invalidated, 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('second', :v_start, CURRENT_TIMESTAMP());

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;

-- ================================================
-- Resume tasks (children first, root last)
-- ================================================
ALTER TASK TASK_LOAD_FACTS RESUME;
ALTER TASK TASK_LOAD_DIMENSIONS_ALBUMS RESUME;
ALTER TASK TASK_LOAD_DIMENSIONS_ARTISTS RESUME;
ALTER TASK TASK_LOAD_STAGING_SONGS RESUME;
ALTER TASK TASK_LOAD_STAGING_ARTISTS RESUME;
ALTER TASK TASK_LOAD_STAGING_ALBUMS RESUME;
ALTER TASK TASK_ROOT_SPOTIFY_PIPELINE RESUME;
