-- All songs with artist and album details [1][2][3]
SELECT * FROM WAREHOUSE_LAYER.SPOTIFY_SONGS_ENRICHED;

-- Songs per artist
SELECT ARTIST_NAME, TOTAL_SONGS, TOTAL_ALBUMS
FROM WAREHOUSE_LAYER.ARTIST_SUMMARY
ORDER BY TOTAL_SONGS DESC;

-- Longest songs
SELECT SONG_NAME, ARTIST_NAME, SONG_DURATION_FORMATTED
FROM WAREHOUSE_LAYER.SPOTIFY_SONGS_ENRICHED
ORDER BY SONG_DURATION_MS DESC
LIMIT 10;

-- Albums released per year [3]
SELECT RELEASE_YEAR, COUNT(*) AS ALBUMS_RELEASED
FROM WAREHOUSE_LAYER.DIM_ALBUMS
WHERE IS_CURRENT = TRUE
GROUP BY RELEASE_YEAR
ORDER BY RELEASE_YEAR DESC;

-- Songs added per month [1]
SELECT
    DATE_TRUNC('month', SONG_ADDED_DATE) AS MONTH,
    COUNT(*) AS SONGS_ADDED
FROM WAREHOUSE_LAYER.FACT_SONGS
GROUP BY 1
ORDER BY 1 DESC;

-- Task history monitoring
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC;