USE SPOTIFY_DB;

USE SCHEMA WAREHOUSE_LAYER;
--Create Dimension Tables with SCD Type 2
-- DIM ARTISTS (SCD Type 2) [2]
CREATE OR REPLACE TABLE DIM_ARTISTS (
    ARTIST_SK           NUMBER AUTOINCREMENT PRIMARY KEY,   -- Surrogate key
    ARTIST_ID           VARCHAR(100),                        -- Natural key
    ARTIST_NAME         VARCHAR(500),
    EXTERNAL_URL        VARCHAR(1000),
    -- SCD Type 2
    EFF_START_DATE      DATE NOT NULL,
    EFF_END_DATE        DATE,
    IS_CURRENT          BOOLEAN DEFAULT TRUE,
    -- Audit
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- DIM ALBUMS (SCD Type 2) [3]
CREATE OR REPLACE TABLE DIM_ALBUMS (
    ALBUM_SK            NUMBER AUTOINCREMENT PRIMARY KEY,
    ALBUM_ID            VARCHAR(100),
    ALBUM_NAME          VARCHAR(500),
    ALBUM_RELEASE_DATE  DATE,
    ALBUM_TOTAL_TRACKS  NUMBER,
    ALBUM_URL           VARCHAR(1000),
    RELEASE_YEAR        NUMBER,
    -- SCD Type 2
    EFF_START_DATE      DATE NOT NULL,
    EFF_END_DATE        DATE,
    IS_CURRENT          BOOLEAN DEFAULT TRUE,
    -- Audit
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- FACT SONGS (Central fact table) [1]
CREATE OR REPLACE TABLE FACT_SONGS (
    SONG_SK                 NUMBER AUTOINCREMENT PRIMARY KEY,
    SONG_ID                 VARCHAR(100) UNIQUE,
    ARTIST_SK               NUMBER REFERENCES DIM_ARTISTS(ARTIST_SK),
    ALBUM_SK                NUMBER REFERENCES DIM_ALBUMS(ALBUM_SK),
    SONG_NAME               VARCHAR(500),
    SONG_DURATION_MS        NUMBER,
    DURATION_MINUTES        NUMBER,
    DURATION_SECONDS        NUMBER,
    SONG_URL                VARCHAR(1000),
    SONG_ADDED_TIMESTAMP    TIMESTAMP_NTZ,
    SONG_ADDED_DATE         DATE,
    -- Audit
    _LOAD_TIMESTAMP         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE            VARCHAR(500)
);
ALTER TABLE WAREHOUSE_LAYER.FACT_SONGS ADD COLUMN IF NOT EXISTS IS_VALID BOOLEAN DEFAULT TRUE;
--Load Dimensions using MERGE

-- MERGE into DIM_ARTISTS [2]
MERGE INTO WAREHOUSE_LAYER.DIM_ARTISTS tgt
USING (
    SELECT * FROM STAGING_LAYER.STG_ARTISTS
    WHERE DATA_QUALITY_FLAG = 'VALID'
) src
ON tgt.ARTIST_ID = src.ARTIST_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
    tgt.ARTIST_NAME  != src.ARTIST_NAME OR
    tgt.EXTERNAL_URL != src.EXTERNAL_URL
) THEN UPDATE SET
    tgt.EFF_END_DATE = CURRENT_DATE() - 1,
    tgt.IS_CURRENT   = FALSE,
    tgt.UPDATED_AT   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN 
INSERT (
    ARTIST_ID, ARTIST_NAME, EXTERNAL_URL,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
    )
VALUES (
    src.ARTIST_ID, src.ARTIST_NAME, src.EXTERNAL_URL,
    CURRENT_DATE(), NULL, TRUE
     );

-- MERGE into DIM_ALBUMS [3]
MERGE INTO WAREHOUSE_LAYER.DIM_ALBUMS tgt
USING (
    SELECT * FROM STAGING_LAYER.STG_ALBUMS
    WHERE DATA_QUALITY_FLAG = 'VALID'
) src
ON tgt.ALBUM_ID = src.ALBUM_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
    tgt.ALBUM_NAME         != src.ALBUM_NAME OR
    tgt.ALBUM_TOTAL_TRACKS != src.ALBUM_TOTAL_TRACKS
) THEN UPDATE SET
    tgt.EFF_END_DATE = CURRENT_DATE() - 1,
    tgt.IS_CURRENT   = FALSE,
    tgt.UPDATED_AT   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE,
    ALBUM_TOTAL_TRACKS, ALBUM_URL, RELEASE_YEAR,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    src.ALBUM_ID, src.ALBUM_NAME, src.ALBUM_RELEASE_DATE,
    src.ALBUM_TOTAL_TRACKS, src.ALBUM_URL, src.RELEASE_YEAR,
    CURRENT_DATE(), NULL, TRUE
);

-- MERGE into FACT_SONGS [1]
MERGE INTO WAREHOUSE_LAYER.FACT_SONGS tgt
USING (
    SELECT
        s.SONG_ID,
        a.ARTIST_SK,
        al.ALBUM_SK,
        s.SONG_NAME,
        s.SONG_DURATION_MS,
        s.DURATION_MINUTES,
        s.DURATION_SECONDS,
        s.SONG_URL,
        s.SONG_ADDED_TIMESTAMP,
        s.SONG_ADDED_DATE,
        s._LOAD_TIMESTAMP,
        s._TRANSFORM_TIMESTAMP
    FROM STAGING_LAYER.STG_SONGS s
    LEFT JOIN WAREHOUSE_LAYER.DIM_ARTISTS a
        ON s.ARTIST_ID = a.ARTIST_ID AND a.IS_CURRENT = TRUE
    LEFT JOIN WAREHOUSE_LAYER.DIM_ALBUMS al
        ON s.ALBUM_ID = al.ALBUM_ID AND al.IS_CURRENT = TRUE
    WHERE s.DATA_QUALITY_FLAG = 'VALID'
) src
ON tgt.SONG_ID = src.SONG_ID
WHEN MATCHED AND (
    tgt.SONG_NAME != src.SONG_NAME
) THEN UPDATE SET
    tgt.SONG_NAME        = src.SONG_NAME,
    tgt._LOAD_TIMESTAMP  = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    SONG_ID, ARTIST_SK, ALBUM_SK, SONG_NAME,
    SONG_DURATION_MS, DURATION_MINUTES, DURATION_SECONDS,
    SONG_URL, SONG_ADDED_TIMESTAMP, SONG_ADDED_DATE, _SOURCE_FILE
)
VALUES (
    src.SONG_ID, src.ARTIST_SK, src.ALBUM_SK, src.SONG_NAME,
    src.SONG_DURATION_MS, src.DURATION_MINUTES, src.DURATION_SECONDS,
    src.SONG_URL, src.SONG_ADDED_TIMESTAMP, src.SONG_ADDED_DATE,
    src._LOAD_TIMESTAMP
);

select * from FACT_SONGS;

