-- Create raw tables and load data from blob storage with full-refresh strategy
-- Co-authored with CoCo

USE DATABASE SPOTIFY_DB;

USE SCHEMA RAW_LAYER;
--Step 1: Create Raw Tables (All VARCHAR - best practice)

CREATE OR REPLACE TABLE RAW_SONGS (
    SONG_ID             VARCHAR(100),
    SONG_NAME           VARCHAR(500),
    SONG_DURATION       VARCHAR(20),
    SONG_URL            VARCHAR(1000),
    SONG_ADDED          VARCHAR(100),
    ALBUM_ID            VARCHAR(100),
    ARTIST_ID           VARCHAR(100),
    -- Metadata -- These = are built-in metadata pseudo-columns that Snowflake automatically provides when you query data from a stage(external or internal)
    _LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR(500),
    _FILE_ROW_NUMBER    NUMBER
);

-- RAW ARTISTS Table [2]
CREATE OR REPLACE TABLE RAW_ARTISTS (
    ARTIST_ID           VARCHAR(100),
    ARTIST_NAME         VARCHAR(500),
    EXTERNAL_URL        VARCHAR(1000),
    -- Metadata
    _LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR(500),
    _FILE_ROW_NUMBER    NUMBER
);

-- RAW ALBUMS Table [3]
CREATE OR REPLACE TABLE RAW_ALBUMS (
    ALBUM_ID            VARCHAR(100),
    ALBUM_NAME          VARCHAR(500),
    ALBUM_RELEASE_DATE  VARCHAR(50),
    ALBUM_TOTAL_TRACKS  VARCHAR(10),
    ALBUM_URL           VARCHAR(1000),
    -- Metadata
    _LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR(500),
    _FILE_ROW_NUMBER    NUMBER
);

--Step 2: Preview Data Before Loading

-- Preview songs
SELECT $1,$2,$3,$4,$5,$6,$7
FROM @STAGE_SONGS/song_transformed.csv
LIMIT 5;

-- Preview artists
SELECT $1,$2,$3
FROM @STAGE_ARTISTS/artist_transformed.csv
LIMIT 5;

-- Preview albums
SELECT $1,$2,$3,$4,$5
FROM @STAGE_ALBUMS/album_transformed.csv
LIMIT 5;
 --Step 3: Load Data with COPY INTO

-- Truncate before reload to ensure fresh data from blob (no duplicates)
TRUNCATE TABLE IF EXISTS RAW_LAYER.RAW_SONGS;
TRUNCATE TABLE IF EXISTS RAW_LAYER.RAW_ARTISTS;
TRUNCATE TABLE IF EXISTS RAW_LAYER.RAW_ALBUMS;

-- Load SONGS [1]
COPY INTO RAW_LAYER.RAW_SONGS (
    SONG_ID, SONG_NAME, SONG_DURATION, SONG_URL,
    SONG_ADDED, ALBUM_ID, ARTIST_ID,
    _SOURCE_FILE, _FILE_ROW_NUMBER
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @STAGE_SONGS/song_transformed.csv
)
FILE_FORMAT = SPOTIFY_CSV_FORMAT
ON_ERROR = 'CONTINUE'
PURGE = FALSE
FORCE = TRUE;


-- Load ARTISTS [2]
COPY INTO RAW_LAYER.RAW_ARTISTS (
    ARTIST_ID, ARTIST_NAME, EXTERNAL_URL,
    _SOURCE_FILE, _FILE_ROW_NUMBER
)
FROM (
    SELECT
        $1, $2, $3,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @STAGE_ARTISTS/artist_transformed.csv
)
FILE_FORMAT = SPOTIFY_CSV_FORMAT
ON_ERROR = 'CONTINUE'
PURGE = FALSE
FORCE = TRUE;

-- Load ALBUMS [3]
COPY INTO RAW_LAYER.RAW_ALBUMS (
    ALBUM_ID, ALBUM_NAME, ALBUM_RELEASE_DATE,
    ALBUM_TOTAL_TRACKS, ALBUM_URL,
    _SOURCE_FILE, _FILE_ROW_NUMBER
)
FROM (
    SELECT
        $1, $2, $3, $4, $5,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @STAGE_ALBUMS/album_transformed.csv
)
FILE_FORMAT = SPOTIFY_CSV_FORMAT
ON_ERROR = 'CONTINUE'
PURGE = FALSE
FORCE = TRUE;

-- Verify row counts
SELECT 'RAW_SONGS'   AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_LAYER.RAW_SONGS   UNION ALL
SELECT 'RAW_ARTISTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_LAYER.RAW_ARTISTS UNION ALL
SELECT 'RAW_ALBUMS'  AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_LAYER.RAW_ALBUMS;

--Step 4: Check Load History
-- Check for any load errors
SELECT TABLE_NAME, STATUS, ROW_COUNT, 
       ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_SONGS',
    START_TIME => DATEADD(hours, -24, CURRENT_TIMESTAMP())
));

SELECT TABLE_NAME, STATUS, ROW_COUNT, 
       ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_ARTISTS',
    START_TIME => DATEADD(hours, -24, CURRENT_TIMESTAMP())
));

SELECT TABLE_NAME, STATUS, ROW_COUNT, 
       ERROR_COUNT, FIRST_ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_ALBUMS',
    START_TIME => DATEADD(hours, -24, CURRENT_TIMESTAMP())
));


DESC RAW_SONGS;
