-- Ad-hoc verification queries for Spotify pipeline
-- Co-authored with CoCo
select * from STAGING_LAYER.STG_ALBUMS

select * from STAGING_LAYER.STG_ARTISTS;

select * from STAGING_LAYER.STG_SONGS;

DROP TASK IF EXISTS TASK_LOAD_STAGING;

ALTER TASK RAW_LAYER.TASK_ROOT_SPOTIFY_PIPELINE RESUME;

USE SCHEMA RAW_LAYER;
select count(*) from RAW_ALBUMS;

select load_status,count(*) from RAW_ALBUMS
group by load_status;

select count(*) from RAW_SONGS;

select count(*) from RAW_ARTISTS;

USE SCHEMA STAGING_LAYER;
select count(*) from STG_ALBUMS;

select count(*) from STG_SONGS;

select count(*) from STG_ARTISTS;

select METADATA$ACTION,count(*) from STREAM_RAW_SONGS 
group by METADATA$ACTION;

select * from STREAM_RAW_SONGS
where METADATA$ACTION = 'INSERT';

select * from STREAM_RAW_ARTISTS
where load_status = 'NEW';


select * from STREAM_RAW_SONGS;

select * from RAW_SONGS r  order by _LOAD_TIMESTAMP desc;

-- Find all records loaded today
SELECT * FROM RAW_SONGS 
WHERE _LOAD_TIMESTAMP = (SELECT MAX(_LOAD_TIMESTAMP) FROM RAW_SONGS); -- 47

SELECT * FROM RAW_ARTISTS WHERE _LOAD_TIMESTAMP = (SELECT MAX(_LOAD_TIMESTAMP) FROM RAW_ARTISTS); -- 51

SELECT * FROM RAW_ALBUMS WHERE _LOAD_TIMESTAMP = (SELECT MAX(_LOAD_TIMESTAMP) FROM RAW_ALBUMS); -- 39 --2026-07-14 04:03:56.539


select count(*) from STAGING_LAYER.STG_SONGS; --47


select count(*) from STAGING_LAYER.STG_ARTISTS; --51


select count(*) from STAGING_LAYER.STG_ALBUMS; --39

select * from WAREHOUSE_LAYER.DIM_ALBUMS i where i.is_current = TRUE; -- 50


select * from WAREHOUSE_LAYER.DIM_ARTISTS i where i.is_current = TRUE; -- 67

select * from WAREHOUSE_LAYER.FACT_SONGS t where t.is_valid = TRUE; -- 129

-- ================================================
-- One-time cleanup: Remove duplicate IS_CURRENT=TRUE records from dimensions
-- Keeps only the record with the highest surrogate key (latest inserted)
-- ================================================

-- Cleanup DIM_ALBUMS duplicates
DELETE FROM WAREHOUSE_LAYER.DIM_ALBUMS
WHERE ALBUM_SK NOT IN (
    SELECT MAX(ALBUM_SK)
    FROM WAREHOUSE_LAYER.DIM_ALBUMS
    WHERE IS_CURRENT = TRUE
    GROUP BY ALBUM_ID
)
AND IS_CURRENT = TRUE;

-- Cleanup DIM_ARTISTS duplicates
DELETE FROM WAREHOUSE_LAYER.DIM_ARTISTS
WHERE ARTIST_SK NOT IN (
    SELECT MAX(ARTIST_SK)
    FROM WAREHOUSE_LAYER.DIM_ARTISTS
    WHERE IS_CURRENT = TRUE
    GROUP BY ARTIST_ID
)
AND IS_CURRENT = TRUE;

-- Cleanup FACT_SONGS duplicates (keep latest per SONG_ID)
DELETE FROM WAREHOUSE_LAYER.FACT_SONGS
WHERE SONG_SK NOT IN (
    SELECT MAX(SONG_SK)
    FROM WAREHOUSE_LAYER.FACT_SONGS
    GROUP BY SONG_ID
);

-- Verify: should match staging counts
SELECT 'DIM_ALBUMS' AS TBL, COUNT(*) AS CURRENT_COUNT FROM WAREHOUSE_LAYER.DIM_ALBUMS WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'DIM_ARTISTS', COUNT(*) FROM WAREHOUSE_LAYER.DIM_ARTISTS WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'FACT_SONGS', COUNT(*) FROM WAREHOUSE_LAYER.FACT_SONGS
UNION ALL
SELECT 'STG_ALBUMS', COUNT(*) FROM STAGING_LAYER.STG_ALBUMS
UNION ALL
SELECT 'STG_ARTISTS', COUNT(*) FROM STAGING_LAYER.STG_ARTISTS
UNION ALL
SELECT 'STG_SONGS', COUNT(*) FROM STAGING_LAYER.STG_SONGS;

UPDATE WAREHOUSE_LAYER.DIM_ARTISTS
SET EFF_END_DATE = EFF_END_DATE - 1
WHERE IS_CURRENT = FALSE AND EFF_END_DATE IS NOT NULL;

UPDATE WAREHOUSE_LAYER.DIM_ALBUMS
SET EFF_END_DATE = EFF_END_DATE - 1
WHERE IS_CURRENT = FALSE AND EFF_END_DATE IS NOT NULL;

-- Update current records: set EFF_START_DATE to today
UPDATE WAREHOUSE_LAYER.DIM_ARTISTS
SET EFF_START_DATE = CURRENT_DATE()
WHERE IS_CURRENT = TRUE;

UPDATE WAREHOUSE_LAYER.DIM_ALBUMS
SET EFF_START_DATE = CURRENT_DATE()
WHERE IS_CURRENT = TRUE;

